app = "cubis-nitter"

kill_signal = "SIGINT"
kill_timeout = 2

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

   [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 4
    timeout = "2s"
