app = "cubis-nitter"

kill_signal = "SIGINT"
kill_timeout = 2

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

